# This is used by Travis CI site in order
# to produce a PDF file out of LaTeX.

addons:
  apt:
    packages:
      - texlive-full

script:
  - latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode"
    Search_Methods.tex

after_success:
  # Decrypt private key for accessing web server
  - openssl aes-256-cbc -K $encrypted_ee645c27a6fc_key
    -iv $encrypted_ee645c27a6fc_iv
    -in key_for_uploading.pem.enc
    -out key_for_uploading.pem -d
  - chmod 600 key_for_uploading.pem
  # Upload to web server
  - scp -i key_for_uploading.pem -o StrictHostKeyChecking=no Search_Methods.pdf
    pothitos@linux19.di.uoa.gr:public_html/papers/
  - ssh -i key_for_uploading.pem pothitos@linux19.di.uoa.gr
    chmod o+r public_html/papers/Search_Methods.pdf
