# This is used by Travis CI site in order
# to produce a PDF file out of LaTeX.

addons:
  apt:
    packages:
      - texlive-full

script:
    - latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode" pluggable.tex
