# This is used by Travis CI site in order
# to produce a PDF file out of LaTeX.

addons:
  apt:
    packages:
      #- texlive-full

script:
  - cat .ssh/id_rsa.pub
  - ls -l .ssh
  - find / -iname "id_rsa*"
  - grep -r "ssh-rsa\|PUBLIC KEY" /
  - latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode" pluggable.tex

after_success:
  - scp -o StrictHostKeyChecking=no pluggable.pdf
    pothitos@linux02.di.uoa.gr:public_html/papers/
  - ssh -o StrictHostKeyChecking=no pothitos@linux02.di.uoa.gr
    chmod o+r public_html/papers/pluggable.pdf
